name: AnnatarHe's blog
author: AnnatarHe
url: https://AnnatarHe.github.io
cdn: http://7xjhkb.com1.z0.glb.clouddn.com/github.io/images
email: iamhele1994@gmail.com
uri: https://github.com/AnnatarHe
paginate: 12
paginate_path: "/pages/:num"
exclude: ['node_modules', '_site']
host: 0.0.0.0
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji
defaults:
  -
    values:
      layout: "post"
