name: AnnatarHe's blog
author: AnnatarHe
url: https://AnnatarHe.github.io
email: iamhele1994@gmail.com
uri: https://github.com/AnnatarHe
paginate: 12
paginate_path: "/page:num/"
exclude: ['node_modules', '_site']
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji
defaults:
  -
    values:
      layout: "post"
